version: 2.1
#on: push ("THis is a an workflow file. To the left is an event specifing to trigger(run) this workflow when someone pushes new code")
workflows:
  test-deploy:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install pyviz, pip install pandas, pip install scipy, pip install plotly
      - run:
          name: Run Tests
          command: npm run test
